# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
        interval: weekly
        time: 08:00
        timezone: Europe/Kyiv
    # @todo uncomment after creation
    #target-branch: "develop"
    commit-message:
        prefix: github-actions
    labels:
      - dependencies
    open-pull-requests-limit: 3
    reviewers:
      - DarkPark
      - aleks-and


  - package-ecosystem: npm
    directory: "/"
    schedule:
        interval: weekly
        time: 08:00
        timezone: Europe/Kyiv
    # @todo uncomment after creation
    #target-branch: "develop"
    commit-message:
        prefix: npm
    labels:
      - dependencies
    open-pull-requests-limit: 3
    reviewers:
      - DarkPark
      - aleks-and
